name: Repo Self-Update

on:
  workflow_call:

permissions:
  contents: write
  pull-requests: write

jobs:
  repo-self-update:
    name: Repo SelfUpdate
    runs-on: ubuntu-latest
    steps:

      - name: Checkout do repositório da aplicação
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout do repositório de templates
        uses: actions/checkout@v4
        with:
          repository: humix-refactor/reusable-workflows
          path: templates
          submodules: false

      
      - name: Atualizar workflows
        run: |
          mkdir -p .github/workflows

          rsync -av --delete \
            templates/.github/workflows/ \
            .github/workflows/

      - name: Criar Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GH_PAT }}
          commit-message: "chore: sync workflows from templates"
          branch: automation/sync-workflows
          delete-branch: true
          title: "chore: sync workflows from templates"
          body: |
            Sync automático de workflows
          base: main

      - name: Habilitar auto-merge
        if: steps.cpr.outputs.pull-request-number
        run: |
          gh pr merge ${{ steps.cpr.outputs.pull-request-number }} \
            --merge \
            --auto
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          