name: Workflow Teste

on:
  workflow_dispatch

jobs:
  teste:
    runs-on: ubuntu-latest
    outputs:
      valor_salvo: ${{ steps.definir.outputs.valor }}
    steps: 
      - name: Primeiro teste
        run: echo "Olá!"
    
      - name: Gravando variáveis de ambiente
        run: echo "TESTE=teste" >> $GITHUB_ENV

      - name: Recuperando variáveis de ambiente
        run: echo $TESTE

      - name: Salvando variável para OUTPUT
        id: definir
        run: echo "valor=1234" >> $GITHUB_OUTPUT
        
  job2:
    needs: teste
    runs-on: ubuntu-latest
    steps:
      - name: Recupera valor do OUTPUT
        run: echo "Valor do primeiro job foi: ${{ needs.teste.outputs.valor_salvo }}"

      
