name: Workflow Teste

on:
  workflow_dispatch

jobs:
  teste:
    runs-on: ubuntu-latest
    outputs:
      valor_salvo: ${{ steps.definir.outputs.valor_salvo }}
    steps: 
      - name: Primeiro teste
        run: echo "Olá!"
    
      - name: Gravando variáveis de ambiente
        run: echo "TESTE=teste" >> $GITHUB_ENV

      - name: Recuperando variáveis de ambiente
        run: echo $TESTE

      - name: Salvando variável para OUTPUT
        id: definir
        run: echo "valor_salvo=1234" >> $GITHUB_OUTPUT
   
  teste_2:
    runs-on: ubuntu-latest
    needs: teste
    steps:
      - name: Recupera valor do output
        run: echo "Valor do output foi: ${{ needs.teste.outputs.valor_salvo }}"
